### ISSUE TITLE
No UI signal if yubikey is configured to require a button press

### ISSUE THREAD

**Issue by Fry-kun** [brush701/keechallenge#15]
Setup: program the key with "Require user input (button press)" option
Whenever opening or saving the DB, the program just hangs until user presses a button on the yubikey.

The UI should pop up something like "Please press the button on yubikey to continue"

**Comment by m451** [comment]
It does so already. See image attached. What version (keepass / plugin / windows) are you running? This sounds like a bug due to a system configuration.

![auth-request](https://cloud.githubusercontent.com/assets/2482535/21961034/23e09530-daff-11e6-86e5-bdf610c462da.png)

**Comment by Fry-kun** [comment]
Hmm, I might've created a bug on the wrong project.. sorry about that!
