### ISSUE TITLE
Unable to connect to Yubikey

### ISSUE THREAD

**Issue by jskvbinmv** [brush701/keechallenge#23]
I recently updated Keepass2 to 2.35 and now I'm getting the error "Unable to connect to Yubikey" when trying to unlock my database.

I'm using Keepass2 v2.35 on Ubuntu 16.10 and keechallenge 1.5.0.

I think the problem might be similar to the one described here:
https://github.com/brush701/keechallenge/issues/20

but I am unable to start KeePass2 as root as it won't start using sudo od gksu.

**Comment by jskvbinmv** [comment]
I have no idea what happened but it's working again...

**Comment by emptywee** [comment]
If anyone runs into this on Ubuntu where you are unable to use KeePass2 with KeeChallenge and Yubikey 5 without root privileges, add a a udev rule under `/etc/udev/rules.d/99-yubikey.rules`:
```
SUBSYSTEM=="usb", ATTRS{product}=="YubiKey OTP+FIDO+CCID", ATTRS{idProduct}=="0407", ATTRS{idVendor}=="1050", MODE="0660", GROUP="yourgroup"
```

where yourgroup is any group you are a member of.

Then run
```
sudo udevadm control --reload-rules && sudo udevadm trigger
```

Ensure the group/mode is set:

```
$ ls -alh /dev/bus/usb/003/005 
crw-rw----+ 1 root yourgroup189, 260 Sep  8 22:01 /dev/bus/usb/003/005
```

You should be good to go with KeePass2 now.
