### ISSUE TITLE
"Padding is invalid and cannot be removed" with NEO 3.4.9

### ISSUE THREAD

**Issue by Gigithecode** [brush701/keechallenge#30]
Hi,

gigi@adam:~/Keepass-sources$ uname -a
Linux adam.gigi.edu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I try to use a second Yubikey NEO with my keepass 2.37 database and KeeChallenge.
The NEO was programmed with the right secret on slot 2 (Challenge / Response + button touch) then both slots was switched.
When I try to open the database with the new configured NEO, Keepass output error message "Padding is invalid and cannot be removed".
I can make it work if I change the master password, keeping the same secret AND checking "Variable length challenge" BUT in this case my old NEO cannot unlock the base anymore!

I assume something changed in NEO firmware between 3.4.6 and 3.4.9 in the management of the secret vs. the key challenge vs. keeChallenge (padding or length management) and make these two firmware levels incompatible to each other regarding HMAC-SHA1 challenge response with keeChallenge...
Are you aware of that issue?

Thanks.

**Comment by gfelbing** [comment]
I have the very same issue, but with different YubiKey-Fimware Versions:

- New Yubikey (not working): 3.5.0
- Old Yubikey (working): 3.4.9

**Comment by Gigithecode** [comment]
Did you find a workaround? I'm still not...

**Comment by jtcmedia** [comment]
Same here:

- Yubikey Neo: 3.3.0 firmware works
- Yubikey 5: 5.1.2 firmware and I get "Padding invalid and cannot be removed"

**Comment by victorclaessen** [comment]
I am experiencing the same issue with a NEO (firmware 3.5.0).

**Comment by victorclaessen** [comment]
I contacted yubico support to see what changed between 3.4.9 and 3.5.0. While they wouldn't say what changed, they did ask that I encourage the KeeChallenge developer @brush701 to contact yubico support so their engineers might be able to help solve this. My yubico support ticket was #75200, so perhaps that would be good to mention.

**Comment by jtcmedia** [comment]
I think this might be abandonware. Issues are still open from 2015 and looking at recent issues, the developer hasn't commented on any.

**Comment by victorclaessen** [comment]
There is always hope :-)

**Comment by victorclaessen** [comment]
I contacted Yubico support, and they were very helpful. I think it turns out that I forgot to change 'variable input' to 'fixed' when I programmed the yubikey. When I tried that, it worked immediately. Perhaps other people that experienced this have made the same mistake? For completeness, please find here below the relevant part of the response from Yubico support:

    When programming the Challenge-Response credential, did you make sure to select Fixed 64 byte input under HMAC-SHA1 Parameters? According to the KeeChallenge page (http://richardbenjaminrush.com/keechallenge/), Variable input, the default setting, is unsupported. I have attached a screenshot for clarification on which setting I'm talking about.
     
    Note that this setting is not available with the YubiKey Manager GUI, only the Personalization Tool (https://www.yubico.com/products/services-software/download/yubikey-personalization-tools/), so, if you used YubiKey Manager, try using the PT and see if you have any better luck.
     
    In case it helps, I have copied the steps I followed to set up KeeChallenge with a YubiKey below.
     
    1. Install KeePass 2 and KeeChallenge
     
     	https://keepass.info/download.html
     	http://richardbenjaminrush.com/keechallenge/
     	https://keepass.info/help/v2/plugins.html (see Plugin Installation and Uninstallation)
     
    2. Install the YubiKey Personalization Tool and generate a Challenge-Response credential in slot 2
     
     	https://www.yubico.com/products/services-software/download/yubikey-personalization-tools/
     	Open the tool, insert your YubiKey, and go Challenge-Response > HMAC-SHA1
     	Select Configuration Slot 2, Fixed 64 byte input, click Generate (copy your secret key somewhere safe), and then Write Configuration
     	Note that if you'd like, you can check the box Require user input (button press) prior to clicking Write Configuration, but it's not necessary
     
     
    3. Register your YubiKey with your KeePass database
     
     	For an existing KeePass database, open the database, then go File > Change Master Key, uncheck Master password (unless you want to change it), check Show expert options, check Key file / provider, select YubiKey challenge-response, and click OK. Paste the secret key you made a copy of earlier into the box, leave Variable Length Challenge? unchecked, and click OK. Click Save.
     
     	For a new KeePass database, on the Create Composite Master Key screen, enter your desired master password, then check Show expert options, check Key file / provider, select YubiKey challenge-response, and click OK. Paste the secret key you made a copy of earlier into the box, leave Variable Length Challenge? unchecked, and click OK. Configure the database settings to your requirements, and click OK. Be sure to save at some point by going File > Save. You will also be prompted to save if you close KeePass without saving your changes.

**Comment by Gigithecode** [comment]
Thanks to victorclaessen who fixed the point.

**Comment by xcy7e** [comment]
But without the [x] tick for variable length, the Secret Key is not accepted by KeePass (even after re-plugging the yubikey).
