### ISSUE TITLE
Invalid composite Key when opening under Ubuntu 18.04.

### ISSUE THREAD

**Issue by MelBourbon** [brush701/keechallenge#33]
I installed keepass2 and added the plugin under Ubuntu 18.04. and want to open a database with the Yubikey Neo which was created and is still working under Windows 10 (sync with Nextcloud). I receive the error "invalid composite key" when opening. Don't know why. What could be the issue? Keyboard layout is correct etc.

**Comment by cheeseandcereal** [comment]
I tried installing and testing under a fresh version of Ubuntu 18.04 and it worked fine.

**Comment by MelBourbon** [comment]
issue considered as stale and closed
