### ISSUE TITLE
Plugin suddenly incompatible after reboot.

### ISSUE THREAD

**Issue by iansebryk** [brush701/keechallenge#36]
out of the blue, i'm now getting this error:

https://drive.google.com/file/d/1QMSyDvX-qy2K8VeAxlihtPgMWH56xhZE/view?usp=sharing

haven't updated, haven't changed.  just rebooted.  i've ripped it out and reinstalled, tried the portable version, downloaded new plugin, tried plugin from backup... nada.  WTF.  i'm locked out from the desktop and unhappy.  i could understand if an update happened, but those are always manual.  what is going on here?  how to i fix this, like RFN?

**Comment by brush701** [comment]
Try deleting the user.config file referenced in the error message. I've never heard of this happening before, but from the error message I'd guess that that file was corrupted somehow.

**Comment by phwiget** [comment]
Did this work? I had the same problem after upgrading to KeePass 2.41. Finally went back to version 2.39.1

**Comment by iansebryk** [comment]
sorry.  was away for a couple days.. i'll check now.

**Comment by iansebryk** [comment]
BAM!  that did it.  thanks for the pointer.  VERY much appreciated.  i'm curious HOW it got corrupted, but that's for another day...  again, thank you.
