### ISSUE TITLE
The expected way to remove Keechallenge from a database?

### ISSUE THREAD

**Issue by sudosammy** [brush701/keechallenge#44]
Is this possible? I'm trying to migrate my database to KeepassXC and need to remove Keechallenge from the database first.

**Comment by Dirk1162** [comment]
The implementation of the challenge response is different between Keepass2 and KeepassXC. Changing the MasterKey gives you the possibility to remove the Keechallenge. After saving the Database you can import it to KeepassXC. There you can set the Challenge Response newly.
Regards Dirk

**Comment by sudosammy** [comment]
Thanks that did the job! I'll close this issue, but I think it would be worthwhile for the documentation to mention that changing the master password is the most sensible way to remove Keechallenge from a database.

**Comment by Sascha198234567** [comment]
this not working on my end
